apiVersion: flightctl.io/v1beta1
kind: ResourceSync
metadata:
  name: default-sync
spec:
  repository: eldar-flightctl     # matches metadata.name above
  path: /examples/fleet.yaml      # same as before
  targetRevision: fake_rs         # your branch in the fork

